maralla/completor.vim

- README.md
Add completor setting for Go programming language. The pattern was extracted from https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/deoplete_go.py#L44
> Add Go usage

- pythonx/completor/__init__.py
- Fix completion start that should return a byte offset
- Use virtual column as cursor position for iterating of strings since
vim.current.window.cursor only return a byte offset
> Fix completion start

- pythonx/completers/cpp.py
On MSYS2, the parameter `-code-completion-at` expects the path to be in Windows path notation with espaced backslashes. This PR changes the cpp completer so it checks for an environment variable `MSYSTEM` and, if it exists, modifies the path accordingly. Converting the *NIX path to Windows is done with a external call to the cygpath tool that comes with msys2.
> cpp completer: Fix clang parameter on MSYS

- Makefile
- README.md
I don't have npm installed so I modified the makefile to detect yarn and use it if available. I'm not sure if this is the best approach.
> Use yarn if available to install tern

- autoload/completor.vim
Currently completor may be triggered in `paste` mode, and this may conflicts with some plugin. For example, see this issue(https://github.com/roxma/vim-paste-easy/issues/7).  
User should use `paste` mode only when they are pasting stuff, so auto completion is not needed in such situation.     
BTW, I also check whether `insert` mode is used, according to this issue(https://github.com/roxma/nvim-completion-manager/issues/78).
> Fix unwanted trigger in paste mode

- autoload/completor.vim
See #109.
Right now, a user can set `completeopt` and have the setting stick right up to the point where they use `completor#completefunc`, which has the side effect of overwriting those settings.
Unless I'm missing something (and this is quite possible!), this repeated overwriting of the user's `completeopt` setting is not integral to completor's functionality.
This diff enables a user to, e.g. `set completeopt=menu,preview` and have it stay that way.
> Do not repeatedly overwrite completeopt setting

- autoload/completor/compat.vim
It seems that sometimes, the ch_status is buffered, but ch_read is
returning nothing. vim_oneshot_handler is stuck in an infinite loop.
Since this is happening in the main thread, vim appears to lockup until
you hit Ctrl+c or something to interrupt eval of this code.
Specifically, I've seen this when using the clang autocompletion on
C-like languages. If I was typing particularly fast, I would see this
issue occur. It was getting annoying.
I ran vim in GDB to try and figure out what was going
on, saw that it was evaling this code inside this function. I then added
logging to this function and confirmed that the problem was here.
Based on my understanding, it is safe to exit the loop early, you might
just not get all your completions...
> Fix vim8 hang when ch_status() == 'buffered' but ch_read returns nothing

- pythonx/completers/go.py
- tests/test_go.py
According to https://github.com/nsf/gocode/issues/461 gocode needs to have as 2nd non-flag parameters real filename. 
Should solve https://github.com/maralla/completor.vim/issues/103
> Add to gocode CLI arguments real filename.

- pythonx/completor/__init__.py
trivial addition to support `tsx` files. I guess it would be wise to either expose this mapping as an extendable `let g:` option, or by default use `b'anything.additional': b'anything'` mapping (would cover javascript, typescript and django use cases)
> Add typescript.jsx to type alias map

- pythonx/completor/__init__.py
If I set a `~` in `gocode` command path, `Completor.parse` will raise `IndexError` since `items` is  `"executing job failed: No such file or directory"`.
> Expand ~ in command path

- README.md
Now [alchemist.vim](https://github.com/slashmili/alchemist.vim) is integrated out of the box with completor.vim.
I sent this feature as PR and was merged today, as you can see here: https://github.com/slashmili/alchemist.vim/pull/136
> Add alchemist.vim as Elixir completer

- .gitignore
- pythonx/completers/go.py
- tests/test_go.py
Sometimes, doc/definition doesn't work, after adding some log, I got the error: `reading size of archive file il: EOF`, I can't provide a minimalist reproducible environment, but I can reproduce it with this: https://github.com/labstack/echo/blob/master/echo.go#L73:26
> Fix the modified content length for go doc/definition

- pythonx/completers/javascript/tern_wrapper.js
Already javascript suggestions aren't case insensitive. Someone should explicitly type for example `setT` to get `setTimeout()` complete suggestion! This patch make them ignore case.
> Make javascript suggestions case insensitive

- doc/completor.txt
- pythonx/completor/__init__.py
I added explicitly allowing {filetype} completions
*g:completor_enable_{filetype}*
Used to explicitly allow {filetype} completions. If this
option is set, only file types in this list can be allowd for
{filetype} completion.
For example enable neosnippet completion for only vim:
>
let g:completor_enable_neosnippet = ['vim']
Default: unset
> Explicitly source

- pythonx/completers/common/filename.py
I allowed below format filename completion.
windows drive letter
(example) c:/
A filepath including spaces
(example) c:/Program Files/
files and directories under a directory in the current directory.
If 'dir_A' direcotry is in the current directory.
(example) dir_B/
> Windows filename

- doc/completor.txt
- pythonx/completers/cpp/__init__.py
I noticed that the automatic generation of placeholders when working on C/C++ is not ideal in my case, and added an option to turn it off. Please merge if you think it might be useful for other developers.
> Added option to allow disabling of placeholder generation in C/C++ code

- README.md
I've been using the configuration in the example in the "Use Tab to select completion" section. I've found the `<cr>` on the last inoremap is counterintuitive. This PR proposes removing it.
The newline is not what I expect when hit enter after tabbing to select the completion I want. I almost always have to delete the newline to get back to the end of the inserted completion, which is where I want to be.
This modified behavior makes the `<cr>` match the behavior in other editors like Atom and VS Code.
> Remove <cr> from tab select example

- autoload/completor.vim
- autoload/completor/action.vim
- plugin/completor.vim
According to the documentation:
```
"[...] The config `completeopt` will be 
overwritten by the value when the completion is triggered and restored
after completion done."
```
This is not what happens in reality though, as `completeopt` is overwritten when entering insert mode, and only restored after leaving it, completely breaking the use of Vim's native completion with the user's `completeopt`.
This pull request fixes this behavior, adapting it to what is described in the documentation and to what is considered a better user experience.
> Fix completeopt not being restored after completion

- plugin/completor.vim
has('python') caused vim to initialize with python 2, disabling python 3
altogether.
- Reverse the check, such that python 3 is used if available.
- Before that, check for pythonx, which initializes according to pyxversion
option if availabe
See :h has-python for more details.
> fix side effect from python support check

- doc/completor.txt
- plugin/completor.vim
- pythonx/completers/common/filename.py
I added g:completor_filename_completion_in_only_comment option, which allow a user to select filename completion in only comment and strings or not.
> add g:completor_filename_completion_in_only_comment

- autoload/completor/daemon.vim
Lower version Vim ( < 8.1 ) does not understand "literal-dict" like "#{}" definition
> Fix "unsafe" call to "popup#safe_hide()"

- autoload/completor/action.vim
The preview window is designed for this task, with handy commands for jumping into it and closing it, all ready to go. I've also enforced some more strict "this is not a real file" settings, left the cursor where it was before the window was opened, and shrunk the opened preview window to a minimal size.
Happy to set up options for any of this functionality, if requested.
> Use preview window to show docs

- pythonx/completers/common/omni.py
bugfix - missing vim.Dictionary type check in omnifunc result, causes a "using Dictionary as string" error in vim.
> add vim.Dictionary in type check of omnifunc result.

- doc/completor.txt
Just a small fix in the documentation.
> Fix typo: allowd -> allowed

- pythonx/completers/python/python_jedi.py
Currently `jump-to-definition` isn't working properly with python3 because PosixPath cannot be converted into json format directly.
This is a quick patch to fix it.
```
[I 210128 20:25:06 __init__:96] Exception e=TypeError('Object of type PosixPath is not JSON serializable')
```
It was hard to find this bug because json dump failure didn't have any output to logger. I think exception handling of json dumping failure should be added too.
> Fixing problem with json dumping failure of PosixPath.

- pythonx/completers/common/buffer.py
I don't have any experience with vim plugins, so this might be totally wrong. But it seems to fix the issue in #302.
EDIT: Also seems to fix #305.
Completor class expects the offset value in the returned dictionaries to be in the number of bytes in the encoding of the current buffer, but Buffer.parse was returning the offset in number of codepoints/runes.
> Fixed offset calculation for Buffer completions; fixes #302

- pythonx/completers/common/buffer.py
Completor also shows the same candidate as the current status.
This confuse, especially,  in buffer completions with multibyte language.
That frequently happens in multibyte languages.
I prohibited buffer completion from doing it.
> Do not show oneself in candidates in Buffer completion

- README.md
Hi @maralla,
I added a completor plugin [completor-vsnip](https://github.com/phongnh/completor-vsnip) for [vim-vsnip](https://github.com/hrsh7th/vim-vsnip) support. I just wanted to add it to README for someone who maybe need it.
Please let me know if I need to update something to get PR merged, thanks.
> Mention completor-vsnip for vim-vsnip support
